rvm:
  - rbx-19mode
  - 2.0.0
  - 1.9.3
  - jruby-19mode
notifications:
  recipients:
    - envygeeks@gmail.com
branches:
  only:
    - master
env:
  - "DBTYPE=mysql2 DBUSER=travis"
  - "DBTYPE=postgresql DBUSER=postgres"
